name: Bug Report
description: Report a bug or issue with RapidRAW
title: "BUG: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.
        
        > **Note:** This template is for reporting bugs and issues only. For feature requests, please use the [Discussions page](../../discussions) instead.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the problem you encountered including error messages (if any).
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Tell us what you thought should happen instead.
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can we reproduce this?
      description: List the steps to recreate the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...

  - type: markdown
    attributes:
      value: "### Your Environment"

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
        - macOS Apple Silicon
        - macOS Intel
        - Ubuntu 24.04
        - Ubuntu 22.04
        - Other Linux
        - Other (please specify in additional info)
    validations:
      required: true

  - type: input
    id: rapidraw-version
    attributes:
      label: RapidRAW Version
      description: What version of RapidRAW are you using?
      placeholder: e.g., v1.2.3
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Any other details that might help us understand the problem?
      placeholder: Any other context, workarounds you've tried, GPU driver version, etc...

  - type: checkboxes
    id: similar-issues
    attributes:
      label: Similar issues
      description: Have you checked for similar issues?
      options:
        - label: I have searched existing issues and didn't find a duplicate
          required: true

  - type: checkboxes
    id: lenses-and-camera-support
    attributes:
      label: Lenses and Camera Support
      description: Does your issue involve specific lenses or camera models?
      options:
        - label: I understand that RapidRAW uses **external libraries** for lenses (lensfun) and raw file support (dnglab), and that not all models may be supported.
          required: true
        - label: I have checked these external libraries for support of **my specific lenses and raw file formats** and acknowledge that my lenses and raw files are supported by them.
          required: true
